/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(TvDecoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a162a5ab162e5cf53b6474117963be6d) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ATV/TvDecoder.h>
// pydoc.h is automatically generated in the build directory
#include <TvDecoder_pydoc.h>

void bind_TvDecoder(py::module& m)
{

    using TvDecoder = ::gr::ATV::TvDecoder;

    py::class_<TvDecoder, gr::block, gr::basic_block, std::shared_ptr<TvDecoder>>(
        m, "TvDecoder", D(TvDecoder))

        .def(py::init(&TvDecoder::make), py::arg("samp_rate"), D(TvDecoder, make))

        ;
}
